Пакет numpy - установка и первое знакомство

In [1]:
import numpy as np

In [8]:
array = np.array([1, 2, 3, 4, 5], dtype=list)
array.dtype

dtype('O')

In [9]:
a = np.array([1, True])
a

array([1, 1])

In [11]:
array[0] = 10
array[0]

10

In [14]:
array[0] = 'a'
array.dtype

dtype('O')

In [15]:
a = np.array([i for i in range(1, 10)])
a[2]

np.int64(3)

In [17]:
a[[1,1,1,1,1]]

array([2, 2, 2, 2, 2])

In [20]:
a[[True for i in range(1, 10)]]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a = np.array([1, 2, 7, 8, 9, 3, 6, 7, 3])
b = a.reshape(3, 3)
b

array([[1, 2, 7],
       [8, 9, 3],
       [6, 7, 3]])

In [24]:
b[1][2]

np.int64(3)

In [25]:
b[(1, 2)]

np.int64(3)