Основные типы данных. Создание массивов функцией array()

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4], dtype='float64')
a

array([1., 2., 3., 4.])

In [4]:
np.sctypeDict

{'bool': numpy.bool,
 'float16': numpy.float16,
 'float32': numpy.float32,
 'float64': numpy.float64,
 'longdouble': numpy.longdouble,
 'complex64': numpy.complex64,
 'complex128': numpy.complex128,
 'clongdouble': numpy.clongdouble,
 'bytes_': numpy.bytes_,
 'str_': numpy.str_,
 'void': numpy.void,
 'object_': numpy.object_,
 'datetime64': numpy.datetime64,
 'timedelta64': numpy.timedelta64,
 'int8': numpy.int8,
 'byte': numpy.int8,
 'uint8': numpy.uint8,
 'ubyte': numpy.uint8,
 'int16': numpy.int16,
 'short': numpy.int16,
 'uint16': numpy.uint16,
 'ushort': numpy.uint16,
 'intc': numpy.intc,
 'uintc': numpy.uintc,
 'int32': numpy.int32,
 'long': numpy.int32,
 'uint32': numpy.uint32,
 'ulong': numpy.uint32,
 'int64': numpy.int64,
 'longlong': numpy.int64,
 'uint64': numpy.uint64,
 'ulonglong': numpy.uint64,
 'intp': numpy.int64,
 'uintp': numpy.uint64,
 'double': numpy.float64,
 'cdouble': numpy.complex128,
 'single': numpy.float32,
 'csingle': numpy.complex64,
 'half': numpy.float16,

In [5]:
print(a * 8)

[ 8. 16. 24. 32.]


In [7]:
a = np.array([1, 2, 3, 4], dtype=str)
print(a)

['1' '2' '3' '4']


In [8]:
np.int16(10.5)

np.int16(10)

In [12]:
np.array("Hello")

array('Hello', dtype='<U5')

In [13]:
np.array([[1, 2], [3,4], [5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]], [[9,10], [11, 12]]])

In [17]:
b[0, 0, 0]

np.int64(1)