Функции автозаполнения, создания матриц и числовых диапазонов

In [1]:
import numpy as np

In [3]:
np.empty((5))

array([0.00000000e+000, 8.91340777e-312, 8.91340777e-312, 8.91340777e-312,
       0.00000000e+000])

In [5]:
np.empty(5, dtype='int32')

array([1172294928,      32761,  237083136,        420,          0],
      dtype=int32)

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.eye(4, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.ones([4, 3], dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [13]:
np.full((3, 3), -1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [15]:
np.asmatrix('1 2 3 4')

matrix([[1, 2, 3, 4]])

In [16]:
np.asmatrix('1, 2; 3, 4')

matrix([[1, 2],
        [3, 4]])

In [17]:
np.asmatrix([[3, 4], [1, 2]])

matrix([[3, 4],
        [1, 2]])

In [18]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
np.diag([(1, 2, 3), (4, 5 , 6)])

array([1, 5])

In [20]:
np.diagflat([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [22]:
np.tri(4, 2)

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [26]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [27]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [28]:
np.vander([1, 2, 3])

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [31]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [34]:
np.cos(np.arange(0, np.pi, 0.1))

array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
        0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
        0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
        0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
       -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
       -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
       -0.9899925 , -0.99913515])

In [42]:
np.linspace(0, np.pi, 4)

array([0.        , 1.04719755, 2.0943951 , 3.14159265])

In [43]:
np.logspace(0, 1, 3)

array([ 1.        ,  3.16227766, 10.        ])

In [44]:
np.geomspace(1, 4, 3)

array([1., 2., 4.])

In [47]:
b = np.copy(a)
b[0] = 100
b

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [48]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
getRange = lambda x, y: 100 * x + y
np.fromfunction(getRange, (2, 2))

array([[  0.,   1.],
       [100., 101.]])

In [51]:
np.fromiter('hello', dtype='<U1')

array(['h', 'e', 'l', 'l', 'o'], dtype='<U1')

In [53]:
np.fromstring('1 2 3', sep=' ')

array([1., 2., 3.])