Свойства и представления массивов, создание их копий

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])

In [3]:
a.dtype

dtype('int64')

In [4]:
a.dtype = np.int8

In [5]:
a

array([1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0,
       0, 0, 0, 0], dtype=int8)

In [6]:
a.size

48

In [7]:
a.shape

(48,)

In [9]:
a.dtype = np.float32

In [10]:
a

array([1.e-45, 0.e+00, 3.e-45, 0.e+00, 4.e-45, 0.e+00, 6.e-45, 0.e+00,
       7.e-45, 0.e+00, 8.e-45, 0.e+00], dtype=float32)

In [11]:
a.itemsize

4

In [12]:
b = np.ones((3,4,5))

In [13]:
b

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [14]:
b.ndim

3

In [15]:
b.shape

(3, 4, 5)

In [16]:
b.shape = 60

In [17]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
b.shape = 12, 5

In [19]:
c = b.reshape(3, 2, 10)

In [20]:
c

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [21]:
b[0, 0] = 10

In [22]:
c

array([[[10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]])

In [23]:
d = b.T

In [24]:
d

array([[10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [25]:
a = np.array([1, 2, 3, 4, 5, 6])

In [26]:
b = a

In [27]:
a.shape = 3, 2

In [28]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
b = a.view()

In [30]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])