Изменение формы массивов, добавление и удаление осей

In [1]:
import numpy as np

In [4]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = a.reshape(2, 5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a.reshape(-1, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
a.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
b.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
b.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a.resize(2, 5)

In [22]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
a.resize(4, 5, refcheck=False)

In [30]:
c = np.tri(5)
c

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [31]:
c.T

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

In [32]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x = x.reshape(1, -1)
x.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [39]:
x_test = np.arange(32).reshape(8, 2, 2)
x_test

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [41]:
x_test4 = np.expand_dims(x_test, axis=0)
x_test4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]]])

In [44]:
x_test4[0, 0, 0, 0] = - 100
x_test

array([[[-100,    1],
        [   2,    3]],

       [[   4,    5],
        [   6,    7]],

       [[   8,    9],
        [  10,   11]],

       [[  12,   13],
        [  14,   15]],

       [[  16,   17],
        [  18,   19]],

       [[  20,   21],
        [  22,   23]],

       [[  24,   25],
        [  26,   27]],

       [[  28,   29],
        [  30,   31]]])

In [45]:
a = np.append(x_test4, x_test4, axis=0)

In [46]:
b = np.delete(a, 0, axis=0)

In [47]:
b = a[np.newaxis, :]