Объединение и разделение массивов

In [1]:
import numpy as np

In [2]:
a = np.array([(1, 2), (3, 4)])
b = np.array([(5, 6), (7, 8)])

In [3]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [4]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
a = np.fromstring('1 2 3 4', sep=' ')
b = np.fromstring('5 6 7 7', sep = ' ')

In [7]:
np.column_stack((a, b))

array([[1., 5.],
       [2., 6.],
       [3., 7.],
       [4., 7.]])

In [9]:
np.row_stack((a, b))

C:\Users\Admin\AppData\Local\Temp\ipykernel_1532\2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1., 2., 3., 4.],
       [5., 6., 7., 7.]])

In [11]:
a = np.arange(1, 13)
b = np.arange(13, 26)

In [13]:
a.resize(3, 3, 2, refcheck=False)
b.resize(3, 3, 2, refcheck=False)

In [16]:
np.concatenate((a, b), axis=0)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]],

       [[25,  0],
        [ 0,  0],
        [ 0,  0]]])

In [17]:
np.r_[[1, 2, 3], 4, 5]

array([1, 2, 3, 4, 5])

In [18]:
np.r_[1:9, 90, 100]

array([  1,   2,   3,   4,   5,   6,   7,   8,  90, 100])

In [19]:
np.c_[1:5]

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
a = np.arange(10)

In [23]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [31]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.vsplit(a, 3)

[array([[1., 1., 1.]]), array([[1., 1., 1.]]), array([[1., 1., 1.]])]